# Generated by Django 4.1.3 on 2022-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=15, null=True, unique=True)),
                ('user_first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('latitude', models.CharField(max_length=15, null=True)),
                ('longitude', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
