# Generated by Django 4.1.3 on 2022-11-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
    ]
