# Generated by Django 4.1.3 on 2022-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_location',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
