# Generated by Django 4.1.3 on 2022-11-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_location_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_location',
            name='latitude',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='longitude',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
