# Generated by Django 4.1.3 on 2022-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_location_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_location',
            name='userId',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
