# Generated by Django 4.1.3 on 2022-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_location_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_location',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_location',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user_location',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_location',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='userId',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
