# Generated by Django 4.1.3 on 2022-11-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_location_gender_user_location_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_location',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
