# Generated by Django 4.1.3 on 2022-11-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_location_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_location',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
